import 'dart:convert';


class ModelCountry {
  String name;
  String flag;
  String code;
  String alpha2;
  String alpha3;
  String currency_code;
  String currency_symbol;
  String currency_name;
  String time_zone;
  double latitude;
  double longitude;

  ModelCountry({
    required this.name,
    required this.flag,
    required this.code,
    required this.alpha2,
    required this.alpha3,
    required this.currency_code,
    required this.currency_symbol,
    required this.currency_name,
    required this.time_zone,
    required this.latitude,
    required this.longitude,
  });

  factory ModelCountry.fromJson(Map<String, dynamic> json) => ModelCountry(
        name: json["name"],
        flag: json["flag"],
        code: json["code"],
        alpha2: json["alpha2"],
        alpha3: json["alpha3"],
        currency_code: json["currency_code"],
        currency_symbol: json["currency_symbol"],
        currency_name: json["currency_name"],
        time_zone: json["time_zone"],
        latitude: json["latitude"],
        longitude: json["longitude"],
      );

  Map<String, dynamic> toJson() => {
        "name": name,
        "flag": flag,
        "code": code,
        "alpha2": alpha2,
        "alpha3": alpha3,
        "currency_code": currency_code,
        "currency_symbol": currency_symbol,
        "currency_name": currency_name,
        "time_zone": time_zone,
        "latitude": latitude,
        "longitude": longitude,
      };

  // static SaveCountry(ModelCountry modelCountry) {
  //   String dddd = jsonEncode(modelCountry.toJson().toString());
  //   ConstantFunctions.saveSharePrefModeString("country", dddd);
  // }
  //
  // static Future<ModelCountry> GetCountry() async {
  //   String ssss = await ConstantFunctions.getSharePrefModeString("country");
  //   return jsonDecode(ssss);
  // }

  static List<ModelCountry> countries = [
    ModelCountry(
        name: "Afghanistan",
        code: "+93",
        flag: "🇦🇫",
        alpha2: "AF",
        alpha3: "AFG",
        currency_code: "AFN",
        currency_symbol: " ؋ ",
        currency_name: "Afghani",
        time_zone: "",
        latitude: 34.52813,
        longitude: 69.17233),

    ModelCountry(
      name: "Albania",
      code: "+355",
      flag: "🇦🇱",
      alpha2: "AL",
      alpha3: "ALB",
      currency_code: "ALL",
      currency_symbol: "Lek",
      currency_name: "Albania Lek",
      time_zone: "",
      latitude: 0.0,
      longitude: 0.0,
    ),

    ModelCountry(
      name: "Algeria",
      code: "+213",
      flag: "🇩🇿",
      alpha2: "DZ",
      alpha3: "DZA",
      currency_code: "DZD",
      currency_symbol: " دج ",
      currency_name: "Algerian dinar",
      time_zone: "",
      latitude: 0.0,
      longitude: 0.0,
    ),

    ModelCountry(
      name: "Andorra",
      code: "+376",
      flag: "🇦🇩",
      alpha2: "AND",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0.0,
      longitude: 0.0,
    ),

    // ModelCountry(
    //   name: "Antarctica",
    //   code: "+672",
    //   flag: "🇦🇶",
    //   alpha2: "",
    //   alpha3: "",
    //   currency_code: "",
    //   currency_symbol: "\$ ",
    //   currency_name: "Dollar",
    //   time_zone: "",
    //   latitude: 0.0,
    //   longitude: 0.0,
    // ),

    ModelCountry(
      name: "Angola",
      code: "+244",
      flag: "🇦🇴",
      alpha2: "",
      alpha3: "",
      currency_code: "AOA",
      currency_symbol: " Kz ",
      currency_name: "Angolan kwanza",
      time_zone: "",
      latitude: 0.0,
      longitude: 0.0,
    ),

    // ModelCountry(
    //   name: "Anguilla",
    //   code: "+1-264",
    //   flag: "🇦🇮",
    //   alpha2: "",
    //   alpha3: "",
    //   currency_code: "",
    //   currency_symbol: "\$ ",
    //   currency_name: "Dollar",
    //   time_zone: "",
    //   latitude: 0.0,
    //   longitude: 0.0,
    // ),

    ModelCountry(
      name: "Antigua and Barbuda",
      code: "+1-268",
      flag: "🇦🇬",
      alpha2: "",
      alpha3: "",
      currency_code: "XCD",
      currency_symbol: " \$ ",
      currency_name: "East Caribbean dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Argentina",
      code: "+54",
      flag: "🇦🇷",
      alpha2: "",
      alpha3: "",
      currency_code: "ARS",
      currency_symbol: " \$ ",
      currency_name: "Argentine peso",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Armenia",
      code: "+374",
      flag: "🇦🇲",
      alpha2: "",
      alpha3: "",
      currency_code: "AMD",
      currency_symbol: " ֏ ",
      currency_name: "Armenian dram",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Aruba",
      code: "+297",
      flag: "🇦🇼",
      alpha2: "ABW",
      alpha3: "AWG",
      currency_code: "AWG",
      currency_symbol: "ƒ ",
      currency_name: "Guilder",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Australia",
      code: "+61",
      flag: "🇦🇺",
      alpha2: "",
      alpha3: "",
      currency_code: "AUD",
      currency_symbol: " A\$ ",
      currency_name: "Australian dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Austria",
      code: "+43",
      flag: "🇦🇹",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Azerbaijan ",
      code: "+994",
      flag: "🇦🇿",
      alpha2: "",
      alpha3: "",
      currency_code: "AZN",
      currency_symbol: " ₼ ",
      currency_name: "Azerbaijani manat",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Bahamas",
      code: "+1-242",
      flag: "🇧🇸",
      alpha2: "",
      alpha3: "",
      currency_code: "BSD",
      currency_symbol: " B\$ ",
      currency_name: "Bahamian dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Bahrain",
      code: "+973",
      flag: "🇧🇭",
      alpha2: "",
      alpha3: "",
      currency_code: "BHD",
      currency_symbol: " .د.ب ",
      currency_name: "Bahraini dinar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Bangladesh",
      code: "+880",
      flag: "🇧🇩",
      alpha2: "",
      alpha3: "",
      currency_code: "BDT",
      currency_symbol: " ৳ ",
      currency_name: "Bangladeshi taka",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Barbados",
      code: "+1-246",
      flag: "🇧🇧",
      alpha2: "",
      alpha3: "",
      currency_code: "BBD",
      currency_symbol: " \$ ",
      currency_name: "Barbadian dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Belarus",
      code: "+375",
      flag: "🇧🇾",
      alpha2: "",
      alpha3: "",
      currency_code: "BYN",
      currency_symbol: " Br ",
      currency_name: "Belarusian ruble",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Belgium",
      code: "+32",
      flag: "🇧🇪",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Belize",
      code: "+501",
      flag: "🇧🇿",
      alpha2: "",
      alpha3: "",
      currency_code: "BZD",
      currency_symbol: " BZ\$ ",
      currency_name: "Belize dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Benin",
      code: "+229",
      flag: "🇧🇯",
      alpha2: "",
      alpha3: "",
      currency_code: "XOF",
      currency_symbol: " CFA ",
      currency_name: "West African CFA franc",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Bhutan",
      code: "+975",
      flag: "🇧🇹",
      alpha2: "",
      alpha3: "",
      currency_code: "BTN",
      currency_symbol: " Nu ",
      currency_name: "Bhutanese ngultrum",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Bolivia",
      code: "+591",
      flag: "🇧🇴",
      alpha2: "",
      alpha3: "",
      currency_code: "BOB",
      currency_symbol: "\$b ",
      currency_name: "Bolivian boliviano",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Bosnia and Herzegovina",
      code: "+387",
      flag: "🇧🇦",
      alpha2: "",
      alpha3: "",
      currency_code: "BAM",
      currency_symbol: "KM ",
      currency_name: "Convertible Marka",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Botswana",
      code: "+267",
      flag: "🇧🇼",
      alpha2: "",
      alpha3: "",
      currency_code: "BWP",
      currency_symbol: " P ",
      currency_name: "Botswana pula",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Brazil",
      code: "+55",
      flag: "🇧🇷",
      alpha2: "",
      alpha3: "",
      currency_code: "BRL",
      currency_symbol: "R\$ ",
      currency_name: "Brazil Real",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Brunei",
      code: "+673",
      flag: "🇧🇳",
      alpha2: "",
      alpha3: "",
      currency_code: "BND",
      currency_symbol: " B\$ ",
      currency_name: "Brunei dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Bulgaria",
      code: "+359",
      flag: "🇧🇬",
      alpha2: "",
      alpha3: "",
      currency_code: "BGN",
      currency_symbol: " лв ",
      currency_name: "Bulgarian lev",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Burkina Faso",
      code: "+226",
      flag: "🇧🇫",
      alpha2: "",
      alpha3: "",
      currency_code: "XOF",
      currency_symbol: " FCFA ",
      currency_name: "Central Africa",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Burundi ",
      code: "+257",
      flag: "🇧🇮",
      alpha2: "",
      alpha3: "",
      currency_code: "BIF",
      currency_symbol: " FBu ",
      currency_name: "Burundian franc",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Cape Verde",
      code: "+238",
      flag: "🇨🇻",
      alpha2: "",
      alpha3: "",
      currency_code: "CVE",
      currency_symbol: "\$ ",
      currency_name: "Cabo Verde",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Cambodia",
      code: "+855",
      flag: "🇰🇭",
      alpha2: "",
      alpha3: "",
      currency_code: "KHR",
      currency_symbol: " ៛ ",
      currency_name: "Cambodian riel",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Cameroon",
      code: "+237",
      flag: "🇨🇲",
      alpha2: "",
      alpha3: "",
      currency_code: "XAF",
      currency_symbol: " FCFA ",
      currency_name: "West Africa",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Canada",
      code: "+1",
      flag: "🇨🇦",
      alpha2: "",
      alpha3: "",
      currency_code: "CAD",
      currency_symbol: " CA\$ ",
      currency_name: "Canadian dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Central African Republic",
      code: "+236",
      flag: "🇨🇫",
      alpha2: "",
      alpha3: "",
      currency_code: "XAF",
      currency_symbol: " FCFA ",
      currency_name: "West Africa",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Chad",
      code: "+235",
      flag: "🇹🇩",
      alpha2: "",
      alpha3: "",
      currency_code: "XAF",
      currency_symbol: " FCFA ",
      currency_name: "West Africa",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Chile",
      code: "+56",
      flag: "🇨🇱",
      alpha2: "",
      alpha3: "",
      currency_code: "CLP",
      currency_symbol: " \$ ",
      currency_name: "Chilean peso",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "China",
      code: "+86",
      flag: "🇨🇳",
      alpha2: "",
      alpha3: "",
      currency_code: "CNY",
      currency_symbol: " ¥ ",
      currency_name: "Chinese yuan",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Colombia",
      code: "+57",
      flag: "🇨🇴",
      alpha2: "",
      alpha3: "",
      currency_code: "COP",
      currency_symbol: " \$ ",
      currency_name: "Colombian peso",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Comoros",
      code: "+269",
      flag: "🇰🇲",
      alpha2: "",
      alpha3: "",
      currency_code: "KMF",
      currency_symbol: " CF ",
      currency_name: "Comorian franc",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    //problem
    ModelCountry(
      name: "Congo",
      code: "+242",
      flag: "🇨🇬",
      alpha2: "",
      alpha3: "",
      currency_code: "CDF",
      currency_symbol: " FC ",
      currency_name: "Congolese franc",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Costa Rica",
      code: "+506",
      flag: "🇨🇷",
      alpha2: "",
      alpha3: "",
      currency_code: "CRC",
      currency_symbol: " ₡ ",
      currency_name: "Costa Rican colón",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    //problem
    ModelCountry(
      name: "Côte d’Ivoire",
      code: "+225",
      flag: "🇨🇮",
      alpha2: "",
      alpha3: "",
      currency_code: "",
      currency_symbol: "\$ ",
      currency_name: "Dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Croatia",
      code: "+385",
      flag: "🇭🇷",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Cuba",
      code: "+53",
      flag: "🇨🇺",
      alpha2: "",
      alpha3: "",
      currency_code: "CUP",
      currency_symbol: " ₱ ",
      currency_name: "Cuban peso",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Cyprus",
      code: "+357",
      flag: "🇨🇾",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Denmark",
      code: "+45",
      flag: "🇩🇰",
      alpha2: "",
      alpha3: "",
      currency_code: "DKK",
      currency_symbol: " kr ",
      currency_name: "Danish krone",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Djibouti",
      code: "+253",
      flag: "🇩🇯",
      alpha2: "",
      alpha3: "",
      currency_code: "DJF",
      currency_symbol: " Fdj ",
      currency_name: "Djiboutian franc",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    //problem with code
    ModelCountry(
      name: "Dominica",
      code: "+1-767",
      flag: "🇩🇲",
      alpha2: "",
      alpha3: "",
      currency_code: "XCD",
      currency_symbol: "\$ ",
      currency_name: "East Caribbean Dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    //problem with code
    ModelCountry(
      name: "Dominican Republic ",
      code: "+1-809, 1-829, 1-849",
      flag: "🇩🇴",
      alpha2: "",
      alpha3: "",
      currency_code: "DOP",
      currency_symbol: " RD\$ ",
      currency_name: "Dominican peso",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Ecuador",
      code: "+593",
      flag: "🇪🇨",
      alpha2: "",
      alpha3: "",
      currency_code: "",
      currency_symbol: "\$ ",
      currency_name: "Dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Egypt",
      code: "+20",
      flag: "🇪🇬",
      alpha2: "",
      alpha3: "",
      currency_code: "EGP",
      currency_symbol: " E£ ",
      currency_name: "Egyptian pound",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    //problem
    ModelCountry(
      name: "El Salvador",
      code: "+503",
      flag: "🇸🇻",
      alpha2: "",
      alpha3: "",
      currency_code: "SVC",
      currency_symbol: "\$ ",
      currency_name: "United States dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Equatorial Guinea",
      code: "+240",
      flag: "🇬🇶",
      alpha2: "",
      alpha3: "",
      currency_code: "XAF",
      currency_symbol: " FCFA ",
      currency_name: "West Africa",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Eritrea",
      code: "+291",
      flag: "🇪🇷",
      alpha2: "",
      alpha3: "",
      currency_code: "ERN",
      currency_symbol: " Nkf ",
      currency_name: "Eritrean nakfa",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
        name: "Estonia",
        code: "+372",
        flag: "🇪🇪",
        alpha2: "EST",
        alpha3: "",
        currency_code: "EUR",
        currency_symbol: " € ",
        currency_name: "Euro",
        time_zone: "",
        latitude: 59.436962,
        longitude: 24.753574),

    ModelCountry(
      name: "Eswatini",
      code: "+268",
      flag: "🇸🇿",
      alpha2: "",
      alpha3: "",
      currency_code: "SZL",
      currency_symbol: " L ",
      currency_name: "Lilangeni",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Ethiopia ",
      code: "+251",
      flag: "🇪🇹",
      alpha2: "",
      alpha3: "",
      currency_code: "ETB",
      currency_symbol: " Br ",
      currency_name: "Ethiopian birr",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Fiji",
      code: "+679",
      flag: "🇫🇯",
      alpha2: "",
      alpha3: "",
      currency_code: "FJD",
      currency_symbol: " \$ ",
      currency_name: "	Fijian dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Finland",
      code: "+358",
      flag: "🇫🇮",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "France",
      code: "+33",
      flag: "🇫🇷",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Gabon",
      code: "+241",
      flag: "🇬🇦",
      alpha2: "",
      alpha3: "",
      currency_code: "XAF",
      currency_symbol: " FCFA ",
      currency_name: "West Africa",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Gambia",
      code: "+220",
      flag: "🇬🇲",
      alpha2: "",
      alpha3: "",
      currency_code: "GMD",
      currency_symbol: " D ",
      currency_name: "Dalasi",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Georgia",
      code: "+995",
      flag: "🇬🇪",
      alpha2: "",
      alpha3: "",
      currency_code: "GEL",
      currency_symbol: " ₾ ",
      currency_name: "Georgian lari",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Germany",
      code: "+49",
      flag: "🇩🇪",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Ghana",
      code: "+233",
      flag: "🇬🇭",
      alpha2: "",
      alpha3: "",
      currency_code: "GHS",
      currency_symbol: " GH₵ ",
      currency_name: "Ghana Cedi",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Greece",
      code: "+30",
      flag: "🇬🇷",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Grenada",
      code: "+1-473",
      flag: "🇬🇩",
      alpha2: "",
      alpha3: "",
      currency_code: "XCD",
      currency_symbol: " \$ ",
      currency_name: "East Caribbean dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Guatemala",
      code: "+502",
      flag: "🇬🇹",
      alpha2: "",
      alpha3: "",
      currency_code: "GTQ",
      currency_symbol: " Q ",
      currency_name: "Guatemalan Quetzal",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Guinea",
      code: "+224",
      flag: "🇬🇳",
      alpha2: "",
      alpha3: "",
      currency_code: "GNF",
      currency_symbol: " FG ",
      currency_name: "Guinean franc",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Guinea-Bissau",
      code: "+245",
      flag: "🇬🇼",
      alpha2: "",
      alpha3: "",
      currency_code: "XOF",
      currency_symbol: " CFA ",
      currency_name: "West African CFA franc",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Guyana",
      code: "+592",
      flag: "🇬🇾",
      alpha2: "",
      alpha3: "",
      currency_code: "GYD",
      currency_symbol: " G\$ ",
      currency_name: "Guyanese dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Haiti",
      code: "+509",
      flag: "🇭🇹",
      alpha2: "",
      alpha3: "",
      currency_code: "HTG",
      currency_symbol: " G ",
      currency_name: "Haitian gourde",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Honduras",
      code: "+504",
      flag: "🇭🇳",
      alpha2: "",
      alpha3: "",
      currency_code: "HNL",
      currency_symbol: " L ",
      currency_name: "Honduran lempira",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Hungary",
      code: "+36",
      flag: "🇭🇺",
      alpha2: "",
      alpha3: "",
      currency_code: "HUF",
      currency_symbol: " Ft ",
      currency_name: "Hungarian forint",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Iceland",
      code: "+354",
      flag: "🇮🇸",
      alpha2: "",
      alpha3: "",
      currency_code: "ISK",
      currency_symbol: " kr ",
      currency_name: "Icelandic króna",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "India",
      code: "+91",
      flag: "🇮🇳",
      alpha2: "",
      alpha3: "",
      currency_code: "INR",
      currency_symbol: " ₹ ",
      currency_name: "Indian rupee",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Indonesia",
      code: "+62",
      flag: "🇮🇩",
      alpha2: "",
      alpha3: "",
      currency_code: "IDR",
      currency_symbol: " Rp ",
      currency_name: "Indonesian rupiah",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Iran",
      code: "+98",
      flag: "🇮🇷",
      alpha2: "",
      alpha3: "",
      currency_code: "IRR",
      currency_symbol: " ﷼ ",
      currency_name: "Iranian rial",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Iraq",
      code: "+964",
      flag: "🇮🇶",
      alpha2: "",
      alpha3: "",
      currency_code: "IQD",
      currency_symbol: " ع.د ",
      currency_name: "Iraqi dinar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Ireland",
      code: "+353",
      flag: "🇮🇪",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Israel",
      code: "+972",
      flag: "🇮🇱",
      alpha2: "",
      alpha3: "",
      currency_code: "ILS",
      currency_symbol: " ₪ ",
      currency_name: "Israeli new shekel",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Italy",
      code: "+39",
      flag: "🇮🇹",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    //problem with code
    ModelCountry(
      name: "Jamaica",
      code: "+1-876",
      flag: "🇯🇲",
      alpha2: "",
      alpha3: "",
      currency_code: "JMD",
      currency_symbol: " J\$ ",
      currency_name: "Jamaican dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Japan",
      code: "+81",
      flag: "🇯🇵",
      alpha2: "",
      alpha3: "",
      currency_code: "JPY",
      currency_symbol: " ¥ ",
      currency_name: "Japanese yen",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Jordan",
      code: "+962",
      flag: "🇯🇴",
      alpha2: "",
      alpha3: "",
      currency_code: "JOD",
      currency_symbol: " ينار ",
      currency_name: "Jordanian dinar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Kazakhstan",
      code: "+7",
      flag: "🇰🇿",
      alpha2: "",
      alpha3: "",
      currency_code: "KZT",
      currency_symbol: " лв ",
      currency_name: "Kazakhstani tenge",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Kenya",
      code: "+254",
      flag: "🇰🇪",
      alpha2: "",
      alpha3: "",
      currency_code: "KES",
      currency_symbol: " KSh ",
      currency_name: "Kenyan shilling",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Kiribati",
      code: "+686",
      flag: "🇰🇮",
      alpha2: "",
      alpha3: "",
      currency_code: "AUD",
      currency_symbol: " \$ ",
      currency_name: "Australian dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Kosovo",
      code: "+383",
      flag: "🇽🇰",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Kuwait",
      code: "+965",
      flag: "🇰🇼",
      alpha2: "",
      alpha3: "",
      currency_code: "KWD",
      currency_symbol: " ك ",
      currency_name: "Kuwaiti dinar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Kyrgyzstan",
      code: "+996",
      flag: "🇰🇬",
      alpha2: "",
      alpha3: "",
      currency_code: "KGS",
      currency_symbol: " som ",
      currency_name: "Kyrgyzstani som",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Laos",
      code: "+856",
      flag: "🇱🇦",
      alpha2: "",
      alpha3: "",
      currency_code: "LAK",
      currency_symbol: " ₭ ",
      currency_name: "Lao kip",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Latvia",
      code: "+371",
      flag: "🇱🇻",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Lebanon",
      code: "+961",
      flag: "🇱🇧",
      alpha2: "",
      alpha3: "",
      currency_code: "LBP",
      currency_symbol: " ل.ل ",
      currency_name: "Lebanese pound",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Lesotho",
      code: "+266",
      flag: "🇱🇸",
      alpha2: "",
      alpha3: "",
      currency_code: "LSL",
      currency_symbol: " L ",
      currency_name: "Lesotho loti",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Liberia",
      code: "+231",
      flag: "🇱🇷",
      alpha2: "",
      alpha3: "",
      currency_code: "LRD",
      currency_symbol: " LD\$ ",
      currency_name: "Liberian dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Libya",
      code: "+218",
      flag: "🇱🇾",
      alpha2: "",
      alpha3: "",
      currency_code: "LYD",
      currency_symbol: " LD ",
      currency_name: "Libyan dinar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Liechtenstein",
      code: "+423",
      flag: "🇱🇮",
      alpha2: "",
      alpha3: "",
      currency_code: "CHF",
      currency_symbol: " CHF ",
      currency_name: "Swiss franc",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Lithuania",
      code: "+370",
      flag: "🇱🇹",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Luxembourg",
      code: "+352",
      flag: "🇱🇺",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Madagascar",
      code: "+261",
      flag: "🇲🇬",
      alpha2: "",
      alpha3: "",
      currency_code: "MGA",
      currency_symbol: " Ar ",
      currency_name: "Malagasy ariary",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Malawi",
      code: "+265",
      flag: "🇲🇼",
      alpha2: "",
      alpha3: "",
      currency_code: "MWK",
      currency_symbol: " K ",
      currency_name: "Malawian kwacha",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Malaysia",
      code: "+60",
      flag: "🇲🇾",
      alpha2: "",
      alpha3: "",
      currency_code: "MYR",
      currency_symbol: " RM ",
      currency_name: "Malaysian ringgit",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Maldives",
      code: "+960",
      flag: "🇲🇻",
      alpha2: "",
      alpha3: "",
      currency_code: "MVR",
      currency_symbol: " MRf ",
      currency_name: "Maldivian rufiyaa",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Mali",
      code: "+223",
      flag: "🇲🇱",
      alpha2: "",
      alpha3: "",
      currency_code: "XOF",
      currency_symbol: " CFA ",
      currency_name: "West African CFA franc",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Malta",
      code: "+356",
      flag: "🇲🇹",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Marshall Islands",
      code: "+692",
      flag: "🇲🇭",
      alpha2: "",
      alpha3: "",
      currency_code: "",
      currency_symbol: "\$ ",
      currency_name: "Dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Mauritania",
      code: "+222",
      flag: "🇲🇷",
      alpha2: "",
      alpha3: "",
      currency_code: "MRU",
      currency_symbol: " UM ",
      currency_name: "Mauritanian ouguiya",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Mauritius",
      code: "+230",
      flag: "🇲🇺",
      alpha2: "",
      alpha3: "",
      currency_code: "MUR",
      currency_symbol: " ₨ ",
      currency_name: "Mauritian rupee",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Mexico",
      code: "+52",
      flag: "🇲🇽",
      alpha2: "",
      alpha3: "",
      currency_code: "MXN",
      currency_symbol: " \$ ",
      currency_name: "Mexican peso",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Micronesia",
      code: "+691",
      flag: "🇫🇲",
      alpha2: "",
      alpha3: "",
      currency_code: "USD",
      currency_symbol: " \$ ",
      currency_name: "United States dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Moldova",
      code: "+373",
      flag: "🇲🇩",
      alpha2: "",
      alpha3: "",
      currency_code: "MDL",
      currency_symbol: " L ",
      currency_name: "Moldovan leu",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Monaco",
      code: "+377",
      flag: "🇲🇨",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Mongolia",
      code: "+976",
      flag: "🇲🇳",
      alpha2: "",
      alpha3: "",
      currency_code: "MNT",
      currency_symbol: " ₮ ",
      currency_name: "Mongolian tögrög",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Montenegro",
      code: "+382",
      flag: "🇲🇪",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Morocco",
      code: "+212",
      flag: "🇲🇦",
      alpha2: "",
      alpha3: "",
      currency_code: "MAD",
      currency_symbol: " DH ",
      currency_name: "Moroccan dirham",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Mozambique",
      code: "+258",
      flag: "🇲🇿",
      alpha2: "",
      alpha3: "",
      currency_code: "MZN",
      currency_symbol: " MT ",
      currency_name: "Mozambican metical",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Myanmar (Burma)",
      code: "+95",
      flag: "🇲🇲",
      alpha2: "",
      alpha3: "",
      currency_code: "MMK",
      currency_symbol: " K ",
      currency_name: "Kyat",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Namibia",
      code: "+264",
      flag: "🇳🇦",
      alpha2: "",
      alpha3: "",
      currency_code: "NAD",
      currency_symbol: " N\$ ",
      currency_name: "Namibian dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Nauru",
      code: "+674",
      flag: "🇳🇷",
      alpha2: "",
      alpha3: "",
      currency_code: "AUD",
      currency_symbol: " A\$ ",
      currency_name: "Australian dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Nepal",
      code: "+977",
      flag: "🇳🇵",
      alpha2: "",
      alpha3: "",
      currency_code: "NPR",
      currency_symbol: " Rs ",
      currency_name: "Nepalese rupee",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Netherlands",
      code: "+31",
      flag: "🇳🇱",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "New Zealand",
      code: "+64",
      flag: "🇳🇿",
      alpha2: "",
      alpha3: "",
      currency_code: "NZD",
      currency_symbol: "\$ ",
      currency_name: "New Zealand dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Nicaragua",
      code: "+505",
      flag: "🇳🇮",
      alpha2: "",
      alpha3: "",
      currency_code: "NIO",
      currency_symbol: " C\$ ",
      currency_name: "Nicaraguan córdoba",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Niger",
      code: "+227",
      flag: "🇳🇪",
      alpha2: "",
      alpha3: "",
      currency_code: "XOF",
      currency_symbol: " CFA ",
      currency_name: "West African CFA franc",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Nigeria",
      code: "+234",
      flag: "🇳🇬",
      alpha2: "",
      alpha3: "",
      currency_code: "NGN",
      currency_symbol: " ₦\$ ",
      currency_name: "Nigerian naira",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "North Korea",
      code: "+850",
      flag: "🇰🇵",
      alpha2: "",
      alpha3: "",
      currency_code: "KPW",
      currency_symbol: " ₩ ",
      currency_name: "North Korean won",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "North Macedonia",
      code: "+389",
      flag: "🇲🇰",
      alpha2: "",
      alpha3: "",
      currency_code: "MKD",
      currency_symbol: " ден ",
      currency_name: "Second Macedonian denar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Norway",
      code: "+47",
      flag: "🇳🇴",
      alpha2: "",
      alpha3: "",
      currency_code: "NOK",
      currency_symbol: " kr ",
      currency_name: "Norwegian krone",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Oman",
      code: "+968",
      flag: "🇴🇲",
      alpha2: "",
      alpha3: "",
      currency_code: "OMR",
      currency_symbol: " ﷼ ",
      currency_name: "Omani rial",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Pakistan",
      flag: "🇵🇰",
      code: "+92",
      alpha2: "PK",
      alpha3: "PAK",
      currency_code: "PKR",
      currency_symbol: " Rs ",
      currency_name: "Pakistani Rupees",
      time_zone: "Asia/Karachi",
      latitude: 33.6844,
      longitude: 73.0479,
    ),

    ModelCountry(
      name: "Palau",
      code: "+680",
      flag: "🇵🇼",
      alpha2: "",
      alpha3: "",
      currency_code: "USD",
      currency_symbol: " \$ ",
      currency_name: "United States dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Palestine",
      code: "+970",
      flag: "🇵🇸",
      alpha2: "",
      alpha3: "",
      currency_code: "ILS",
      currency_symbol: " ₪ ",
      currency_name: "Israeli new shekel",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Panama",
      code: "+507",
      flag: "🇵🇦",
      alpha2: "",
      alpha3: "",
      currency_code: "PAB",
      currency_symbol: " B/. ",
      currency_name: "Panamanian balboa",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    //problem
    ModelCountry(
      name: "Papua New Guinea",
      code: "+675",
      flag: "🇵🇬",
      alpha2: "",
      alpha3: "",
      currency_code: "",
      currency_symbol: "\$ ",
      currency_name: "Dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Paraguay",
      code: "+595",
      flag: "🇵🇾",
      alpha2: "",
      alpha3: "",
      currency_code: "PYG",
      currency_symbol: " ₲ ",
      currency_name: "Paraguayan guaraní",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Peru",
      code: "+51",
      flag: "🇵🇪",
      alpha2: "",
      alpha3: "",
      currency_code: "PEN",
      currency_symbol: " S/. ",
      currency_name: "Peruvian sol",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Philippines",
      code: "+63",
      flag: "🇵🇭",
      alpha2: "",
      alpha3: "",
      currency_code: "PHP",
      currency_symbol: " ₱ ",
      currency_name: "Philippine peso",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Poland",
      code: "+48",
      flag: "🇵🇱",
      alpha2: "",
      alpha3: "",
      currency_code: "PLN",
      currency_symbol: " zł ",
      currency_name: "Polish zloty",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Portugal",
      code: "+351",
      flag: "🇵🇹",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Qatar",
      code: "+974",
      flag: "🇶🇦",
      alpha2: "",
      alpha3: "",
      currency_code: "QAR",
      currency_symbol: " ﷼ ",
      currency_name: "Qatari riyal",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Romania",
      code: "+40",
      flag: "🇷🇴",
      alpha2: "",
      alpha3: "",
      currency_code: "RON",
      currency_symbol: " lei ",
      currency_name: "Romanian leu",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Russia",
      code: "+7",
      flag: "🇷🇺",
      alpha2: "",
      alpha3: "",
      currency_code: "RUB",
      currency_symbol: " ₽ ",
      currency_name: "Russian ruble",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Rwanda",
      code: "+250",
      flag: "🇷🇼",
      alpha2: "",
      alpha3: "",
      currency_code: "RWF",
      currency_symbol: " R₣ ",
      currency_name: "Rwandan franc",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Saint Kitts and Nevis",
      code: "+1-869",
      flag: "🇰🇳",
      alpha2: "",
      alpha3: "",
      currency_code: "XCD",
      currency_symbol: " \$ ",
      currency_name: "East Caribbean dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    //problem with code
    ModelCountry(
      name: "Saint Lucia",
      code: "+1-758",
      flag: "🇱🇨",
      alpha2: "",
      alpha3: "",
      currency_code: "XCD",
      currency_symbol: " \$ ",
      currency_name: "East Caribbean dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    //problem with code
    ModelCountry(
      name: "St. Vincent & Grenadines",
      code: "+1-784",
      flag: "🇻🇨",
      alpha2: "",
      alpha3: "",
      currency_code: "XCD",
      currency_symbol: " \$ ",
      currency_name: "East Caribbean dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    //problem with currency symbol
    ModelCountry(
      name: "Samoa",
      code: "+685",
      flag: "🇼🇸",
      alpha2: "",
      alpha3: "",
      currency_code: "WST",
      currency_symbol: " \$ ",
      currency_name: "Samoan tala",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "San Marino",
      code: "+378",
      flag: "🇸🇲",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    //problem with currency symbol
    ModelCountry(
      name: "Sao Tome and Principe",
      code: "+239",
      flag: "🇸🇹",
      alpha2: "",
      alpha3: "",
      currency_code: "STD",
      currency_symbol: " \$ ",
      currency_name: "São Tomé and Príncipe dobra",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Saudi Arabia",
      code: "+966",
      flag: "🇸🇦",
      alpha2: "",
      alpha3: "",
      currency_code: "SAR",
      currency_symbol: " ﷼ ",
      currency_name: "Saudi riyal",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Senegal",
      code: "+221",
      flag: "🇸🇳",
      alpha2: "",
      alpha3: "",
      currency_code: "XOF",
      currency_symbol: " CFA ",
      currency_name: "West African CFA franc",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Serbia",
      code: "+381",
      flag: "🇷🇸",
      alpha2: "",
      alpha3: "",
      currency_code: "RSD",
      currency_symbol: " Дин ",
      currency_name: "Serbian dinar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Seychelles",
      code: "+248",
      flag: "🇸🇨",
      alpha2: "",
      alpha3: "",
      currency_code: "SCR",
      currency_symbol: " Rs ",
      currency_name: "Seychelles Rupee",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Sierra Leone",
      code: "+232",
      flag: "🇸🇱",
      alpha2: "",
      alpha3: "",
      currency_code: "SLL",
      currency_symbol: " Le ",
      currency_name: "Sierra Leonean leone",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Singapore",
      code: "+65",
      flag: "🇸🇬",
      alpha2: "",
      alpha3: "",
      currency_code: "SGD",
      currency_symbol: " S\$ ",
      currency_name: "Singapore dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Slovakia",
      code: "+421",
      flag: "🇸🇰",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Slovenia",
      code: "+386",
      flag: "🇸🇮",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    //============== Completed ========================================

    //============== Between ========================================

    ModelCountry(
      name: "Solomon Islands",
      code: "+677",
      flag: "🇸🇧",
      alpha2: "",
      alpha3: "",
      currency_code: "SBD",
      currency_symbol: " \$ ",
      currency_name: "Solomon Islands dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Somalia",
      code: "+252",
      flag: "🇸🇴",
      alpha2: "",
      alpha3: "",
      currency_code: "SOS",
      currency_symbol: " Sh.So. ",
      currency_name: "Somalia Shilling",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "South Africa",
      code: "+27",
      flag: "🇿🇦",
      alpha2: "",
      alpha3: "",
      currency_code: "ZAR",
      currency_symbol: " R ",
      currency_name: "South african rand",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "South Korea",
      code: "+82",
      flag: "🇰🇷",
      alpha2: "",
      alpha3: "",
      currency_code: "KRW",
      currency_symbol: " ₩ ",
      currency_name: "Korea (South) Won",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Spain",
      code: "+34",
      flag: "🇪🇸",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Sri Lanka",
      code: "+94",
      flag: "🇱🇰",
      alpha2: "",
      alpha3: "",
      currency_code: "LKR",
      currency_symbol: " ₨ ",
      currency_name: "Sri Lankan rupee",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Sudan",
      code: "+249",
      flag: "🇸🇩",
      alpha2: "",
      alpha3: "",
      currency_code: "SDG",
      currency_symbol: " SDG ",
      currency_name: "Sudanese pound",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "South Sudan",
      code: "+211",
      flag: "🇸🇸",
      alpha2: "",
      alpha3: "",
      currency_code: "SSP",
      currency_symbol: " SS£ ",
      currency_name: "South Sudanese pound",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Suriname",
      code: "+597",
      flag: "🇸🇷",
      alpha2: "",
      alpha3: "",
      currency_code: "SRD",
      currency_symbol: " Sr\$ ",
      currency_name: "Surinamese dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Sweden",
      code: "+46",
      flag: "🇸🇪",
      alpha2: "",
      alpha3: "",
      currency_code: "SEK",
      currency_symbol: " kr ",
      currency_name: "Swedish krona",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Switzerland",
      code: "+41",
      flag: "🇨🇭",
      alpha2: "",
      alpha3: "",
      currency_code: "CHF",
      currency_symbol: " CHF ",
      currency_name: "Swiss franc",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Syria",
      code: "+963",
      flag: "🇸🇾",
      alpha2: "",
      alpha3: "",
      currency_code: "SYP",
      currency_symbol: " £S ",
      currency_name: "Syrian pound",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Taiwan",
      code: "+886",
      flag: "🇹🇼",
      alpha2: "",
      alpha3: "",
      currency_code: "TWD",
      currency_symbol: " NT\$ ",
      currency_name: "New Taiwan dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Tajikistan",
      code: "+992",
      flag: "🇹🇯",
      alpha2: "",
      alpha3: "",
      currency_code: "TJS",
      currency_symbol: " TJS ",
      currency_name: "Somoni",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Tanzania",
      code: "+255",
      flag: "🇹🇿",
      alpha2: "",
      alpha3: "",
      currency_code: "TZS",
      currency_symbol: " TSh ",
      currency_name: "Tanzanian shilling",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Thailand",
      code: "+66",
      flag: "🇹🇭",
      alpha2: "",
      alpha3: "",
      currency_code: "THB",
      currency_symbol: " ฿ ",
      currency_name: "Thai baht",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Togo",
      code: "+228",
      flag: "🇹🇬",
      alpha2: "",
      alpha3: "",
      currency_code: "XOF",
      currency_symbol: " CFA ",
      currency_name: "West African CFA franc",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    //problem with currency symbol
    ModelCountry(
      name: "Tonga",
      code: "+676",
      flag: "🇹🇴",
      alpha2: "",
      alpha3: "",
      currency_code: "TOP",
      currency_symbol: " \$ ",
      currency_name: "Tongan pa'anga",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Trinidad & Tobago",
      code: "+1-868",
      flag: "🇹🇹",
      alpha2: "",
      alpha3: "",
      currency_code: "TTD",
      currency_symbol: " TT\$ ",
      currency_name: "Trinidad and Tobago dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Tunisia",
      code: "+216",
      flag: "🇹🇳",
      alpha2: "",
      alpha3: "",
      currency_code: "TND",
      currency_symbol: " د.ت ",
      currency_name: "Tunisian dinar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Turkey",
      code: "+90",
      flag: "🇹🇷",
      alpha2: "",
      alpha3: "",
      currency_code: "TRY",
      currency_symbol: " ₺ ",
      currency_name: "Turkish lira",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Turkmenistan",
      code: "+993",
      flag: "🇹🇲",
      alpha2: "",
      alpha3: "",
      currency_code: "TMT",
      currency_symbol: "\$ ",
      currency_name: "Turkmen new manat",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Tuvalu",
      code: "+688",
      flag: "🇹🇻",
      alpha2: "",
      alpha3: "",
      currency_code: "AUD",
      currency_symbol: " A\$ ",
      currency_name: "Australian dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Uganda",
      code: "+256",
      flag: "🇺🇬",
      alpha2: "",
      alpha3: "",
      currency_code: "UGX",
      currency_symbol: " USh ",
      currency_name: "Ugandan shilling",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Ukraine",
      code: "+380",
      flag: "🇺🇦",
      alpha2: "",
      alpha3: "",
      currency_code: "UAH",
      currency_symbol: " ₴ ",
      currency_name: "Ukrainian hryvna",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "United Arab Emirates",
      code: "+971",
      flag: "🇦🇪",
      alpha2: "",
      alpha3: "",
      currency_code: "AED",
      currency_symbol: " AED ",
      currency_name: "Emirati dirham",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "United Kingdom",
      code: "+44",
      flag: "🇬🇧",
      alpha2: "",
      alpha3: "",
      currency_code: "GBP",
      currency_symbol: " £ ",
      currency_name: "Pounds sterling",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "United States",
      code: "+1",
      flag: "🇺🇸",
      alpha2: "",
      alpha3: "",
      currency_code: "USD",
      currency_symbol: " \$ ",
      currency_name: "Dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Uruguay",
      code: "+598",
      flag: "🇺🇾",
      alpha2: "",
      alpha3: "",
      currency_code: "UYU",
      currency_symbol: "\$U ",
      currency_name: "Uruguayan peso",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Uzbekistan",
      code: "+998",
      flag: "🇺🇿",
      alpha2: "",
      alpha3: "",
      currency_code: "UZS",
      currency_symbol: " som ",
      currency_name: "Uzbekistan som",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    //problem with currency symbol
    ModelCountry(
      name: "Vanuatu",
      code: "+678",
      flag: "🇻🇺",
      alpha2: "",
      alpha3: "",
      currency_code: "VUV",
      currency_symbol: " \$ ",
      currency_name: "Vanuatu vatu",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Vatican City",
      code: "+379",
      flag: "🇻🇦",
      alpha2: "",
      alpha3: "",
      currency_code: "EUR",
      currency_symbol: " € ",
      currency_name: "Euro",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Venezuela",
      code: "+58",
      flag: "🇻🇪",
      alpha2: "",
      alpha3: "",
      currency_code: "VED",
      currency_symbol: " Bs. ",
      currency_name: "Venezuelan bolívar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Vietnam",
      code: "+84",
      flag: "🇻🇳",
      alpha2: "",
      alpha3: "",
      currency_code: "VND",
      currency_symbol: " ₫ ",
      currency_name: "Vietnamese đồng",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Yemen",
      code: "+967",
      flag: "🇾🇪",
      alpha2: "",
      alpha3: "",
      currency_code: "YER",
      currency_symbol: " ﷼ ",
      currency_name: "Yemeni rial",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    //problem with currency symbol
    ModelCountry(
      name: "Zambia",
      code: "+260",
      flag: "🇿🇲",
      alpha2: "",
      alpha3: "",
      currency_code: "ZMW",
      currency_symbol: " ZMW ",
      currency_name: "Zambian kwacha",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),

    ModelCountry(
      name: "Zimbabwe",
      code: "+263",
      flag: "🇿🇼",
      alpha2: "",
      alpha3: "",
      currency_code: "USD",
      currency_symbol: " \$ ",
      currency_name: "United States dollar",
      time_zone: "",
      latitude: 0,
      longitude: 0,
    ),
  ];
}
